Add GraphQL chapter
infinum/wordpress-handbook pull request #135
Opened 2021-03-25 15:12 UTC by gabriel-glo

2021-03-25 15:16 UTC, goranalkovic-infinum commented on WordPress as API/WordPress GraphQL API.md
> +WordPress REST API can be extended to support [GraphQL](https://graphql.org/). GraphQL is a query language for your API and it acts as a separate layer between WordPress REST API and application that
```suggestion
WordPress REST API can be extended to support [GraphQL](https://graphql.org/). GraphQL is a query language for your API and it acts as a separate layer between the WordPress REST API and the application using data from the API.
```

2021-03-25 15:18 UTC, goranalkovic-infinum commented on WordPress as API/WordPress GraphQL API.md
> +GraphQL in WordPress can be enables via [WPGraphQL plugin](https://www.wpgraphql.com/). It is a free plugin, hosted on the WordPress plugin repository. It comes with a pretty useful GraphiQL tool tha
```suggestion
GraphQL in WordPress can be enabled via the [WPGraphQL plugin](https://www.wpgraphql.com/). It is a free plugin, hosted on the WordPress plugin repository. It comes with a pretty useful _GraphiQL_ tool that allows you to preview GraphQL schemas and test queries.
```

2021-03-25 15:19 UTC, goranalkovic-infinum commented on WordPress as API/WordPress GraphQL API.md
> +To test the queries click on resources on the left sidebar to drill down in their structure and see what is available. For example, to get all posts and show their title, link, excerpt and content, t
```suggestion
To test the queries click on resources in the left sidebar. You can drill down in their structure and see what is available. For example, to get all posts and show their title, link, excerpt and content, the query would look like this:
```

2021-03-25 15:20 UTC, goranalkovic-infinum commented on WordPress as API/WordPress GraphQL API.md
> +To combine multiple resources in one query you just continue to select the in the sidebar or write them down in query editor. For this example we will query all post categories and all posts.
```suggestion
To combine multiple resources in one query you can keep selecting resources the in the sidebar or add them in the query editor. For this example we will query all post categories and all posts.
```

2021-03-25 15:20 UTC, goranalkovic-infinum commented on WordPress as API/WordPress GraphQL API.md
> +This is just a start of interacting with GraphiQL and more examples and guides can be found in plugins [documentation](https://www.wpgraphql.com/docs/).
```suggestion
This is just a start of interacting with GraphiQL and more examples and guides can be found in the plugin's [documentation](https://www.wpgraphql.com/docs/).
```

2021-03-25 15:21 UTC, goranalkovic-infinum commented on WordPress as API/WordPress GraphQL API.md
> +Apps that will use WordPress GraphQL API will need to send HTTP POST requests to the GraphQL endpoint and provide the query in request body. WPGraphQL plugin registers this endpoint and by default it
```suggestion
Apps that use the WordPress GraphQL API will need to send HTTP POST requests to the GraphQL endpoint and provide the query in the request body. WPGraphQL plugin registers this endpoin, the default is `http://your-domain.com/graphql/`.
```

2021-03-25 15:21 UTC, goranalkovic-infinum commented on WordPress as API/WordPress GraphQL API.md
> +### Adding new resources to the WordPress GraphQL
```suggestion
### Adding new resources to WordPress GraphQL
```

2021-03-25 15:22 UTC, goranalkovic-infinum commented on WordPress as API/WordPress GraphQL API.md
> +To add a custom post or a taxonomy types to the GraphQL schema you need to provide additional arguments to the register functions.
```suggestion
To add a custom post or a taxonomy type to the GraphQL schema you need to provide additional arguments to the register functions.
```

2021-03-25 15:22 UTC, goranalkovic-infinum commented on WordPress as API/WordPress GraphQL API.md
> +GraphQL will use the single and plural name to register new GraphQL [types](https://graphql.org/learn/schema/#type-system) which will be used in queries.
```suggestion
GraphQL will use the single and plural names to register new GraphQL [types](https://graphql.org/learn/schema/#type-system) which will be used in queries.
```

2021-03-25 15:22 UTC, goranalkovic-infinum commented on WordPress as API/WordPress GraphQL API.md
> +#### Adding new GraphQL type
```suggestion
#### Adding a new GraphQL type
```

2021-03-25 15:23 UTC, goranalkovic-infinum commented on WordPress as API/WordPress GraphQL API.md
> +WPGraphQL comes with a lot of registered types and you can use them to register more complex fields. Most of the time you'll use [scalar](https://www.wpgraphql.com/docs/default-types-and-fields/#scal
```suggestion
WPGraphQL comes with a lot of registered types and you can use them to register more complex fields. Most of the time you'll use [scalar](https://www.wpgraphql.com/docs/default-types-and-fields/#scalars) (simple) types but you can register your own custom types. You can learn more about this in the [documentation](https://www.wpgraphql.com/docs/default-types-and-fields).
```

2021-03-25 15:24 UTC, goranalkovic-infinum commented on WordPress as API/WordPress GraphQL API.md
> +To add additional fields to the registered types you'd use [register_graphql_fields](https://www.wpgraphql.com/functions/register_graphql_fields/) or [register_graphql_field](https://www.wpgraphql.co
```suggestion
To add additional fields to the registered types you can use [register_graphql_fields](https://www.wpgraphql.com/functions/register_graphql_fields/) or [register_graphql_field](https://www.wpgraphql.com/functions/register_graphql_field/) functions inside the callback of [graphql_register_types](https://www.wpgraphql.com/actions/graphql_register_types/) action.
```

2021-03-25 15:24 UTC, goranalkovic-infinum commented on WordPress as API/WordPress GraphQL API.md
> +The example above is for the field that returns a string value. You can register fields that will return more complex value. For example, you want to register image field that will return values of m
```suggestion
The example above is for the field that returns a string value. You can register fields that will return more complex values. For example, you might want to register an image field that will return values of multiple images. For each image you will have URL of the image and the alt text.
```

2021-03-25 15:25 UTC, goranalkovic-infinum commented on WordPress as API/WordPress GraphQL API.md
> +To do that you need to first register a custom image type (remember that name must be unique) that will have two sub-fields: URL and alt text. In `register_graphql_field` function you will define a t
```suggestion
To do that you need to first register a custom image type (remember that the name must be unique!) that will have two sub-fields: URL and alt text. In the `register_graphql_field` function you will define a field type of of image fields.
```

2021-03-25 15:25 UTC, goranalkovic-infinum commented on WordPress as API/WordPress GraphQL API.md
> +						'description' => esc_html__('alt value of the image', 'your-textdomain'),
```suggestion
						'description' => esc_html__('Image alt text', 'your-textdomain'),
```

2021-03-25 15:26 UTC, goranalkovic-infinum submitted a review, later dismissed
Couple of typos and suggestions, otherwise nice job 🎉

2021-03-25 16:27 UTC, dingo-d commented on WordPress as API/WordPress GraphQL API.md
> +GraphQL in WordPress can be enables via [WPGraphQL plugin](https://www.wpgraphql.com/). It is a free plugin, hosted on the WordPress plugin repository. It comes with a pretty useful GraphiQL tool tha
```suggestion
GraphQL in WordPress can be enabled via [WPGraphQL plugin](https://www.wpgraphql.com/). It is a free plugin, hosted on the WordPress plugin repository. It comes with a pretty useful GraphiQL tool that allows you to preview GraphQL schema and test out some queries.
```

2021-03-25 16:28 UTC, dingo-d commented on WordPress as API/WordPress GraphQL API.md
> +This is just a start of interacting with GraphiQL and more examples and guides can be found in plugins [documentation](https://www.wpgraphql.com/docs/).
```suggestion
This is just the start of interacting with GraphiQL. More examples and guides can be found in plugin's [documentation](https://www.wpgraphql.com/docs/).
```

2021-03-25 16:31 UTC, dingo-d requested changes
Left a few comments

2021-03-26 07:34 UTC, gabriel-glo commented on WordPress as API/WordPress GraphQL API.md
> +To do that you need to first register a custom image type (remember that name must be unique) that will have two sub-fields: URL and alt text. In `register_graphql_field` function you will define a t
Doesn't work in this context

2021-03-26 11:26 UTC, dingo-d approved these changes

2021-03-29 06:50 UTC, IvanGrginovInf approved these changes

2021-03-29 07:53 UTC, iruzevic approved these changes

2021-03-29 07:58 UTC, merged